name: "brasil Client"
version: "1.0"

client:
  organization: brasil
  credentialStore:
    path: "./keys"
    cryptoStore:
      path: "./keys"

channels:
  datoschannel:
    orderers:
      - orderer.arcelormittal.com
    peers:
      peer0.asturias.arcelormittal.com:
        endorsingPeer: true
        chaincodeQuery: true
        ledgerQuery: true
        eventSource: true
      peer0.brasil.arcelormittal.com:
        endorsingPeer: true
        chaincodeQuery: true
        ledgerQuery: true
        eventSource: true
      peer0.chicago.arcelormittal.com:
        endorsingPeer: true
        chaincodeQuery: true
        ledgerQuery: true
        eventSource: true

organizations:
  brasil:
    mspid: brasilMSP
    peers:
      - peer0.brasil.arcelormittal.com
    certificateAuthorities:
      - ca.brasil.arcelormittal.com

peers:
  peer0.brasil.arcelormittal.com:
    url: grpc://localhost:11051

orderers:
  orderer.arcelormittal.com:
    url: grpc://172.31.0.84:7050
