name: "asturias Client"
version: "1.0"

client:
  organization: asturias
  credentialStore:
    path: "./keys"
    cryptoStore:
      path: "./keys"

channels:
  datoschannel:
    orderers:
      - orderer.antonio.com
    peers:
      peer0.asturias.antonio.com:
        endorsingPeer: true
        chaincodeQuery: true
        ledgerQuery: true
        eventSource: true
      peer0.brasil.antonio.com:
        endorsingPeer: true
        chaincodeQuery: true
        ledgerQuery: true
        eventSource: true
      peer0.chicago.antonio.com:
        endorsingPeer: true
        chaincodeQuery: true
        ledgerQuery: true
        eventSource: true

organizations:
  asturias:
    mspid: asturiasMSP
    peers:
      - peer0.asturias.antonio.com
    certificateAuthorities:
      - ca.asturias.antonio.com

peers:
  peer0.asturias.antonio.com:
    url: grpc://localhost:7051

orderers:
  orderer.antonio.com:
    url: grpc://172.31.0.84:7050
